"""
    GitHub Actions workflow generator for automated visibility revert.

    Creates a scheduled GitHub Actions workflow that reverts published repos
    back to private after a configurable number of days. This is the safety
    net — even if you forget to revert manually, the scheduled action will
    do it for you.

    Generates two artifacts:
      1. `.github/workflows/revert-visibility.yml` — the Actions workflow
      2. `repos-to-revert.txt` — the repo list consumed by the workflow
"""

using Dates

# ---------------------------------------------------------------------------
# Workflow generation
# ---------------------------------------------------------------------------

"""
    generate_revert_workflow(owner::String, repos::Vector{String}, days::Int, output_dir::String) -> String

Generate a GitHub Actions workflow that reverts `repos` to private after `days`
days, plus a `repos-to-revert.txt` file listing the repos.

Creates the output directory structure if it doesn't exist. Returns the path
to the generated workflow YAML file.

# Arguments
- `owner`: GitHub username or org that owns the repositories.
- `repos`: Vector of repository names to include in the revert.
- `days`: Number of days from now to schedule the revert (e.g., 14).
- `output_dir`: Root directory for output (workflow goes in `.github/workflows/`
  underneath this, and `repos-to-revert.txt` goes directly in it).

# Example
```julia
generate_revert_workflow("s3nik", ["repo-a", "repo-b"], 14, "scheduler-output/")
```
"""
function generate_revert_workflow(owner::String, repos::Vector{String}, days::Int, output_dir::String)::String
    # Calculate the revert date and cron expression
    revert_date = Dates.today() + Dates.Day(days)
    revert_minute = 0
    revert_hour = 9  # 9:00 AM UTC

    # Cron: minute hour day month *
    cron_expr = "$(revert_minute) $(revert_hour) $(Dates.day(revert_date)) $(Dates.month(revert_date)) *"

    # --- Create directory structure ---
    workflow_dir = joinpath(output_dir, ".github", "workflows")
    mkpath(workflow_dir)

    # --- Write repos-to-revert.txt ---
    revert_list_path = joinpath(output_dir, "repos-to-revert.txt")
    open(revert_list_path, "w") do io
        for repo in repos
            println(io, repo)
        end
    end
    @info "Wrote repos-to-revert.txt" path=revert_list_path repos=length(repos)

    # --- Generate the workflow YAML ---
    workflow_path = joinpath(workflow_dir, "revert-visibility.yml")

    workflow_content = """
    # Auto-generated by GHAudit — Revert repository visibility to private
    #
    # Scheduled to run on $(Dates.format(revert_date, "yyyy-mm-dd")) at $(lpad(revert_hour, 2, '0')):$(lpad(revert_minute, 2, '0')) UTC
    # This workflow reads repos-to-revert.txt and sets each repo back to private.
    #
    # To use:
    #   1. Push this repo (with .github/workflows/ and repos-to-revert.txt) to GitHub
    #   2. The workflow will trigger automatically on the scheduled date
    #   3. You can also trigger it manually via the Actions tab (workflow_dispatch)

    name: Revert Repo Visibility

    on:
      schedule:
        - cron: '$(cron_expr)'
      workflow_dispatch:
        inputs:
          confirm:
            description: 'Type YES to confirm revert'
            required: true
            default: 'YES'

    permissions:
      contents: read

    jobs:
      revert:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Revert repos to private
            env:
              GH_TOKEN: \${{ secrets.GH_AUDIT_TOKEN }}
              OWNER: $(owner)
            run: |
              echo "Starting visibility revert for \$OWNER"
              echo "=================================="

              if [ ! -f repos-to-revert.txt ]; then
                echo "ERROR: repos-to-revert.txt not found"
                exit 1
              fi

              TOTAL=\$(wc -l < repos-to-revert.txt | tr -d ' ')
              COUNT=0
              FAILED=0

              while IFS= read -r repo; do
                # Skip empty lines and comments
                [[ -z "\$repo" || "\$repo" == \\#* ]] && continue

                COUNT=\$((COUNT + 1))
                echo "[\$COUNT/\$TOTAL] Reverting \$OWNER/\$repo to private..."

                if gh repo edit "\$OWNER/\$repo" --visibility private --accept-visibility-change-consequences 2>&1; then
                  echo "  Done."
                else
                  echo "  FAILED to revert \$OWNER/\$repo"
                  FAILED=\$((FAILED + 1))
                fi

                # Rate limit: 1 second between calls
                sleep 1
              done < repos-to-revert.txt

              echo "=================================="
              echo "Revert complete: \$COUNT processed, \$FAILED failed"

              if [ \$FAILED -gt 0 ]; then
                echo "::warning::Some repos failed to revert. Check logs above."
                exit 1
              fi
    """

    open(workflow_path, "w") do io
        write(io, workflow_content)
    end
    @info "Wrote revert workflow" path=workflow_path schedule=cron_expr revert_date=revert_date

    # --- Print user instructions ---
    instructions = """

    ============================================================
    REVERT WORKFLOW GENERATED
    ============================================================

    Files created:
      $(abspath(workflow_path))
      $(abspath(revert_list_path))

    To activate the automatic revert:

      1. Create a new GitHub repo (e.g., '$(owner)/repo-scheduler'):
         gh repo create $(owner)/repo-scheduler --private

      2. Initialize and push:
         cd $(abspath(output_dir))
         git init
         git add .
         git commit -m "Add visibility revert workflow"
         git remote add origin https://github.com/$(owner)/repo-scheduler.git
         git push -u origin main

      3. Add a Personal Access Token as a repo secret:
         gh secret set GH_AUDIT_TOKEN -R $(owner)/repo-scheduler

         The token needs 'repo' scope to change visibility.

      4. The workflow will automatically run on $(Dates.format(revert_date, "yyyy-mm-dd"))
         at $(lpad(revert_hour, 2, '0')):$(lpad(revert_minute, 2, '0')) UTC, reverting $(length(repos)) repos to private.

      5. To trigger manually before the scheduled date:
         gh workflow run revert-visibility.yml -R $(owner)/repo-scheduler

    ============================================================
    """

    println(instructions)

    return abspath(workflow_path)
end
